// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mint_message.proto

/*
Package mint is a generated protocol buffer package.

It is generated from these files:
	mint_message.proto

It has these top-level messages:
	MintPayload
*/
package mint

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MintPayload struct {
	Partition int32  `protobuf:"varint,1,opt,name=partition" json:"partition,omitempty"`
	Number    string `protobuf:"bytes,2,opt,name=number" json:"number,omitempty"`
	Time      int64  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *MintPayload) Reset()                    { *m = MintPayload{} }
func (m *MintPayload) String() string            { return proto.CompactTextString(m) }
func (*MintPayload) ProtoMessage()               {}
func (*MintPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MintPayload) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *MintPayload) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *MintPayload) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*MintPayload)(nil), "mint.MintPayload")
}

func init() { proto.RegisterFile("mint_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcd, 0xcc, 0x2b,
	0x89, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x89, 0x29, 0x85, 0x73, 0x71, 0xfb, 0x66, 0xe6, 0x95, 0x04, 0x24, 0x56, 0xe6, 0xe4, 0x27,
	0xa6, 0x08, 0xc9, 0x70, 0x71, 0x16, 0x24, 0x16, 0x95, 0x64, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x21, 0x04, 0x84, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a, 0x73, 0x93, 0x52,
	0x8b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xcc,
	0xdc, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0x8b, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x26, 0x01, 0x99, 0x7b, 0x00, 0x00, 0x00,
}
