http:
  port: 9909
zookeeper:
  type: zookeeper
  host: zookeeper.default
  port: 2181
  path: /matrixs
  level: 2
mq:
  type: kafka
  host: kafka.default
  port: 9092
scheduler:
  second: 10
  partition: 3
